Repository wecode-bootcamp-korea/28-1st-KurlyFlower-frontend, pull requests merged in 2022-01, with the labels that each got.

#4 Fix setting - master branch 기초 세팅 사항 추가
  .vscode/settings.json
  src/styles/variables.scss
Labels: Status: 리뷰 요청

#5 [Add][28기 한상일]공용으로 사용하는 nav 컴포넌트 레이아웃 완료
  src/ pages/Login/Login.js
  src/components/CSCENTERLIST.js
  src/components/Nav.js
  src/components/Nav.scss
  src/components/Navlogo.js
  src/components/Navlogo.scss
Labels: Status: 리뷰 요청

#2 [28기 이가윤] 최종 리뷰 수정사항 반영
  .vscode/settings.json
  package-lock.json
  package.json
  public/data/main/MainProductList1.json
  public/data/main/MainProductList2.json
  public/data/main/MainProductList3.json
  public/data/main/MainProductList4.json
  public/data/main/banners.json
  public/data/main/filter1.json
  public/data/main/filter2.json
  public/data/main/filter3.json
  public/data/main/filter4.json
  public/images/main/1.png
  public/images/main/2.png
  public/images/main/3.png
  public/images/main/4.png
  public/images/main/5.png
  public/images/main/6.png
  public/images/main/carrot.jpg
  src/ pages/Main/Banner/Banner.js
  src/ pages/Main/Banner/Banner.scss
  src/ pages/Main/Collection/Collection.js
  src/ pages/Main/Collection/Collection.scss
  src/ pages/Main/FilterProduct/FilterProduct.js
  src/ pages/Main/FilterProduct/FilterProduct.scss
  src/ pages/Main/LoadMoreProducts/LoadMoreProducts.js
  src/ pages/Main/LoadMoreProducts/LoadMoreProducts.scss
  src/ pages/Main/Main.js
  src/ pages/Main/Main.scss
  src/ pages/Main/Nav/Nav.js
  src/ pages/Main/Nav/Nav.scss
  src/ pages/Main/Products/Products.js
  src/ pages/Main/Products/Products.scss
  src/ pages/Main/Skeleton/Skeleton.js
  src/ pages/Main/Skeleton/Skeleton.scss
Labels: Status: 추가 기능 구현중

#3 [28기 유호진][Add]백엔드 통신 완료/페이지 전환 구현중
  .vscode/settings.json
  public/data/productData.json
  src/ pages/Main/Main.js
  src/ pages/ProductList/ProductList.js
  src/ pages/ProductList/ProductList.scss
  src/ pages/ProductList/components/Menu/Menu.js
  src/ pages/ProductList/components/Menu/Menu.scss
  src/ pages/ProductList/components/MenuList/MenuList.js
  src/ pages/ProductList/components/MenuList/MenuList.scss
  src/ pages/ProductList/components/SortMenu/SortMenu.js
  src/ pages/ProductList/components/SortMenu/SortMenu.scss
  src/styles/variables.scss
Labels: Status: Accepted, Status: 추가 기능 구현중

#7 [Modify]20220103 리뷰사항 반영
  src/ pages/Login/Login.js
  src/components/CSCENTERLIST.js
  src/components/Nav.js
Labels: Status: 리뷰 요청

#1 [28기 한상일][Modify]20220104 리뷰사항 반영완료 + 백엔드 통신완료
  src/ pages/Login/Login.js
  src/ pages/Login/Login.scss
  src/ pages/Signup/BtnModal.js
  src/ pages/Signup/BtnModal.scss
  src/ pages/Signup/SIGNUPAGREE.js
  src/ pages/Signup/Signup.js
  src/ pages/Signup/Signup.scss
  src/ pages/Signup/TABLETH.js
  src/components/footer.js
  src/components/footer.scss
Labels: Status: Conflict 해결 요청, Status: 수정 요청

#11 [28기 한상일][Add]20220106 상세페이지 백엔드 통신 완료
  src/ pages/Login/Login.js
  src/ pages/Login/Login.scss
  src/ pages/ProductDetail/PRODUCTPAGE.js
  src/ pages/ProductDetail/ProductDetail.js
  src/ pages/ProductDetail/ProductDetail.scss
  src/ pages/ProductList/components/Menu/Menu.js
  src/ pages/Signup/Signup.js
  src/ pages/Signup/Signup.scss
  src/Router.js
  src/components/footer.js
  src/components/footer.scss
Labels: Status: 리뷰 요청
